/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as GraphqlRouteImport } from './routes/graphql'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReposRepositoryIdSettingsRouteImport } from './routes/repos.$repositoryId.settings'
import { Route as SessionWorkItemIdTelemetryRouteImport } from './routes/session.$workItemId.telemetry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlRoute = GraphqlRouteImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRepositoryIdSettingsRoute =
  ReposRepositoryIdSettingsRouteImport.update({
    id: '/$repositoryId/settings',
    path: '/$repositoryId/settings',
    getParentRoute: () => ReposRoute,
  } as any)
const SessionWorkItemIdTelemetryRoute =
  SessionWorkItemIdTelemetryRouteImport.update({
    id: '/session/$workItemId/telemetry',
    path: '/session/$workItemId/telemetry',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/graphql': typeof GraphqlRoute
  '/kanban': typeof KanbanRoute
  '/repos': typeof ReposRouteWithChildren
  '/settings': typeof SettingsRoute
  '/repos/$repositoryId/settings': typeof ReposRepositoryIdSettingsRoute
  '/session/$workItemId/telemetry': typeof SessionWorkItemIdTelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/graphql': typeof GraphqlRoute
  '/kanban': typeof KanbanRoute
  '/repos': typeof ReposRouteWithChildren
  '/settings': typeof SettingsRoute
  '/repos/$repositoryId/settings': typeof ReposRepositoryIdSettingsRoute
  '/session/$workItemId/telemetry': typeof SessionWorkItemIdTelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/graphql': typeof GraphqlRoute
  '/kanban': typeof KanbanRoute
  '/repos': typeof ReposRouteWithChildren
  '/settings': typeof SettingsRoute
  '/repos/$repositoryId/settings': typeof ReposRepositoryIdSettingsRoute
  '/session/$workItemId/telemetry': typeof SessionWorkItemIdTelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completed'
    | '/graphql'
    | '/kanban'
    | '/repos'
    | '/settings'
    | '/repos/$repositoryId/settings'
    | '/session/$workItemId/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/completed'
    | '/graphql'
    | '/kanban'
    | '/repos'
    | '/settings'
    | '/repos/$repositoryId/settings'
    | '/session/$workItemId/telemetry'
  id:
    | '__root__'
    | '/'
    | '/completed'
    | '/graphql'
    | '/kanban'
    | '/repos'
    | '/settings'
    | '/repos/$repositoryId/settings'
    | '/session/$workItemId/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletedRoute: typeof CompletedRoute
  GraphqlRoute: typeof GraphqlRoute
  KanbanRoute: typeof KanbanRoute
  ReposRoute: typeof ReposRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SessionWorkItemIdTelemetryRoute: typeof SessionWorkItemIdTelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql': {
      id: '/graphql'
      path: '/graphql'
      fullPath: '/graphql'
      preLoaderRoute: typeof GraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$repositoryId/settings': {
      id: '/repos/$repositoryId/settings'
      path: '/$repositoryId/settings'
      fullPath: '/repos/$repositoryId/settings'
      preLoaderRoute: typeof ReposRepositoryIdSettingsRouteImport
      parentRoute: typeof ReposRoute
    }
    '/session/$workItemId/telemetry': {
      id: '/session/$workItemId/telemetry'
      path: '/session/$workItemId/telemetry'
      fullPath: '/session/$workItemId/telemetry'
      preLoaderRoute: typeof SessionWorkItemIdTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReposRouteChildren {
  ReposRepositoryIdSettingsRoute: typeof ReposRepositoryIdSettingsRoute
}

const ReposRouteChildren: ReposRouteChildren = {
  ReposRepositoryIdSettingsRoute: ReposRepositoryIdSettingsRoute,
}

const ReposRouteWithChildren = ReposRoute._addFileChildren(ReposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletedRoute: CompletedRoute,
  GraphqlRoute: GraphqlRoute,
  KanbanRoute: KanbanRoute,
  ReposRoute: ReposRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SessionWorkItemIdTelemetryRoute: SessionWorkItemIdTelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
