/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as GraphqlRouteImport } from './routes/graphql'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ReposRouteImport } from './routes/repos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlRoute = GraphqlRouteImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/graphql': typeof GraphqlRoute
  '/kanban': typeof KanbanRoute
  '/repos': typeof ReposRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/graphql': typeof GraphqlRoute
  '/kanban': typeof KanbanRoute
  '/repos': typeof ReposRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completed': typeof CompletedRoute
  '/graphql': typeof GraphqlRoute
  '/kanban': typeof KanbanRoute
  '/repos': typeof ReposRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/completed' | '/graphql' | '/kanban' | '/repos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/completed' | '/graphql' | '/kanban' | '/repos'
  id: '__root__' | '/' | '/completed' | '/graphql' | '/kanban' | '/repos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletedRoute: typeof CompletedRoute
  GraphqlRoute: typeof GraphqlRoute
  KanbanRoute: typeof KanbanRoute
  ReposRoute: typeof ReposRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql': {
      id: '/graphql'
      path: '/graphql'
      fullPath: '/graphql'
      preLoaderRoute: typeof GraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletedRoute: CompletedRoute,
  GraphqlRoute: GraphqlRoute,
  KanbanRoute: KanbanRoute,
  ReposRoute: ReposRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
