#!/usr/bin/env bun
import { readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const drizzleRoot = resolve(packageRoot, "../db-schema/drizzle")
const outFile = join(packageRoot, "src/lib/embedded-migrations.gen.ts")

const entries = readdirSync(drizzleRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort((a, b) => a.localeCompare(b))

const sourceLines: string[] = []

for (const name of entries) {
  const sql = readFileSync(join(drizzleRoot, name, "migration.sql"), "utf8")
  if (sql.trim().length === 0) {
    throw new Error(`Empty migration SQL: ${name}`)
  }
  sourceLines.push(
    `  {\n    name: ${JSON.stringify(name)},\n    sql: ${JSON.stringify(sql)},\n  },`,
  )
}

const content = `/** Generated by scripts/generate-embedded-migrations.ts — do not edit. */
export const embeddedMigrationSources: ReadonlyArray<{
  readonly name: string
  readonly sql: string
}> = [
${sourceLines.join("\n")}
]
`

writeFileSync(outFile, content)
console.log(
  `Wrote ${outFile} (${entries.length} migrations from ${drizzleRoot})`,
)
